server:
  port: 8082

spring:
  application:
    name: kafka
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      request-enrichment-receita: request-enrichment-receita
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: true
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer